version: '2'

services:
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    restart: always
    ports:
      - 9000:9000
      - 9092:9092
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube_db:5432/sonar
    volumes:
      - conf:/opt/sonarqube/conf
      - data:/opt/sonarqube/data
      - extensions:/opt/sonarqube/extensions
      - bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  sonarqube_db:
    image: postgres
    container_name: sonarqube_db
    restart: always
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  conf:
  data:
  extensions:
  bundled-plugins:
  postgresql:
  postgresql_data:
