version: '2'
services:

  oss-openam:
    build: 
      context: .

      # 'args' can use only building.
      args:
        - HTTP_PROXY
        - HTTPS_PROXY
        - NO_PROXY
        - JENKINS_HOST=
        - JENKINS_OPENAM_WAR_PATH=
        - JDK_VERSION=1.8.0
        - CATALINA_OPTS="-Xmx2048m -server"

  # usage:
  #
  #   docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
  #   docker exec -it themi-wam_themi-wam_1 bash -c '/opt/initialize.sh'
  #
  #   # build only:   docker-compose -f docker-compose.yml -f docker-compose.dev.yml build --no-cache
  #   # install only: docker exec -it themi-wam_themi-wam_1 bash -c 'cd /opt/tswam-installer && ./install.sh'
