#!/bin/bash
#
# Determine the parameter matrix to build on DockerHub

set -eu

# ===== tag patterns =====
#
# trial (tomcat80, preconfig=y)
# tomcat80 (tomcat80, preconfig=y)
#
# cent7-tomcat80 (centos7, tomcat80, not configured)
# cent7-tomcat80-trial (centos7, tomcat80, preconfig=y)
#
# cent7-jdk11-trial (centos7, jdk11, preconfig=y)
# cent7-tomcat85-trial (centos7, tomcat85, preconfig=y)
# cent7-tomcat90-trial (centos7, tomcat90, preconfig=y)

case ${DOCKER_TAG} in
    *trial )
        OPENAM_PRECONFIGURE='y'
        ;;
esac

case ${DOCKER_TAG} in
    cent7-* )
        IMAGE_FROM='centos:centos7'
        RUN_CMD='"/sbin/init"'
        SUDO_TOMCAT_CMD='sudo -u tomcat '

        case ${DOCKER_TAG} in
            *-tomcat85* )
                CENTOS7_TOMCAT_MAJOR='8'
                CENTOS7_TOMCAT_VERSION='8.5.38'
                ;;
            *-tomcat90* )
                CENTOS7_TOMCAT_MAJOR='9'
                CENTOS7_TOMCAT_VERSION='9.0.16'
                ;;
            * )
                # Default value is Tomcat 8.0
                CENTOS7_TOMCAT_MAJOR='8'
                CENTOS7_TOMCAT_VERSION='8.0.53'
                ;;
        esac

        case ${DOCKER_TAG} in
            *-jdk11* )
                CENTOS7_JDK_VERSION='11'
                ;;
            * )
                # Default value is JDK 1.8
                CENTOS7_JDK_VERSION='1.8.0'
                ;;
        esac
        ;;

    * )
        # Default value is official 'tomcat:8.0-jre8' image
        IMAGE_FROM='tomcat:8.0-jre8'
        RUN_CMD='"catalina.sh", "run"'
        SUDO_TOMCAT_CMD=''
        ;;
esac

docker build \
    --build-arg IMAGE_FROM=${IMAGE_FROM} \
    --build-arg RUN_CMD=${RUN_CMD} \
    --build-arg OPENAM_PRECONFIGURE=${OPENAM_PRECONFIGURE:-"n"} \
    --build-arg CENTOS7_TOMCAT_MAJOR=${CENTOS7_TOMCAT_MAJOR:-""} \
    --build-arg CENTOS7_TOMCAT_VERSION=${CENTOS7_TOMCAT_VERSION:-""} \
    --build-arg CENTOS7_JDK_VERSION=${CENTOS7_JDK_VERSION:-""} \
    -f ${DOCKERFILE_PATH:-"Dockerfile"} \
    -t ${IMAGE_NAME} \
    .
