version: '3.5'
services:

  devenv-xrdp:
    build: 
      context: .

      # 'args' can use only building.
      args:
        - HTTP_PROXY
        - HTTPS_PROXY
        - NO_PROXY
        - XRDP_USER=xrdpuser
        - XRDP_PASSWORD=P@ssw0rd
        - JENKINS_GIT_USER=Jenkins Admin
        - JENKINS_GIT_MAIL=jenkins_admin@example.com
        - JDK_DEFAULT_VERSION=1.8.0
        - PHANTOMJS_PACKAGE=phantomjs-2.1.1-linux-x86_64
        - MAVEN_LOCALREPO_PATH=/home/xrdpuser/.m2/project-repository/Branch_openam-14.0.0-SNAPSHOT_13.5.0_tswam-5.1.1

  # usage:
  #
  #   docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
  #   docker exec -it ${CONTAINER_NAME} bash -c '/opt/initialize.sh'
  #
  #   # build only:   docker-compose -f docker-compose.yml -f docker-compose.dev.yml build --no-cache
