version: "3.7"

services:

    # --------------------
    # am-am1, am-am2
    #   127.x.x.21 127.x.x.22
    #   xxx-am-am1.example.com xxx-am-am2.example.com
    #   http://xxx-am-am1.example.com:8080/openam
    #   http://xxx-am-am2.example.com:8080/openam
    #   http://xxx-am-lb.example.com/openam
    #
    am-am1:
        build:
          context: ./resources/am-am
          args:
            AM_IMAGE: ${AM_TOMCAT_IMAGE_TAG}
            MVN_VERSION: ${MVN_VERSION}
        image: am-am
        container_name: ${AM_AM1_HOSTNAME}
        domainname: ${COMMON_DOMAIN_NAME}
        # Replicate the properties defined in .env to environment variables in the container
        env_file: .env
        networks:
            # Allow containers to resolve names with each other
            - fixed_am_network
        ports:
            # 8080(Tomcat http), 8009(Tomcat ajp), 4444(OpenDJ Admin), 50389(OpenDJ LDAP)
            - "${AM_AM1_IP}:8080:8080"
            - "${AM_AM1_IP}:50389:50389"
        volumes:
            - /dev/urandom:/dev/random:ro
            - am-shared-m2-dir:/root/.m2
            - am-shared-webapp-dir:${AM_WEBAPP_DIR}
            - am-am1-base-dir:${AM_BASE_DIR}
            - ./workspace:/opt/workspace
            - ./resources/am-am/server.ajp-with-secret.xml:/usr/local/tomcat/conf/server.xml
            - ./resources/am-am/context.legacycookie-enable.xml:/usr/local/tomcat/conf/context.xml
        restart: unless-stopped

volumes:
    # OpenAM Local
    am-shared-m2-dir:
    am-shared-webapp-dir:
    am-am1-base-dir:

networks:
    # Allow containers to resolve names with each other
    fixed_am_network:
        driver: bridge
